### ISSUE TITLE
Cant set volume

### ISSUE THREAD

**Issue by LarkinZero** [kovalev-sergey/homebridge-sony-audio#18]
My device is HT-CT800
homebridge-sony-audio v1.2.0
![IMG_3760](https://user-images.githubusercontent.com/6387162/152336677-fb9f81db-d5bf-4c89-8f2f-7751d9f2c2c0.PNG)

**Comment by kovalev-sergey** [comment]
Hi @LarkinZero 
This plugin implements volume control in accordance with Apple recommendations.
You can control the volume through Apple TV Remote. It is in the control center.
![IMG_0186](https://user-images.githubusercontent.com/36263763/152825946-bccbc08d-1e77-4a7f-b805-4e1c550cdfcd.jpg)

If it is not displayed, go to Settings ->  Control Centre and enable it.

After that you can control volume, arrow buttons and play/stop (volume changes via hardware volume buttons).
![IMG_0187](https://user-images.githubusercontent.com/36263763/152827163-38770bfd-302b-44a2-923d-84132521eab6.PNG)

You can read more [here](https://support.apple.com/guide/tv/use-ios-or-ipados-control-center-atvb701cadc1/tvos)

**Comment by LarkinZero** [comment]
Thank you for your reply, now I know how to control the volume.
