### ISSUE TITLE
Question: what does the Inputs selection do?

### ISSUE THREAD

**Issue by nielsth** [kovalev-sergey/homebridge-sony-audio#3]
I've installed this plugin for my HT-ZF9 and set-up was really easy. The Home app lets you select Inputs under Settings, but what does it do? The available channels in the Details screen under the Power button don't change with this.

![IMG_8343](https://user-images.githubusercontent.com/13969232/112629077-1d8aa080-8e34-11eb-865f-d2a8df521e03.PNG)
![IMG_8344](https://user-images.githubusercontent.com/13969232/112629090-211e2780-8e34-11eb-99bb-a7973486bceb.PNG)

**Comment by kovalev-sergey** [comment]
To be honest, I don't quite understand the purpose of these settings either. There is no clear explanation in the HomeKit API, moreover, for me personally, these selectors are displayed, and sometimes not. An attempt to clarify this issue has failed. If I come across some information on how to work with this, I will definitely implement this function.
