### ISSUE TITLE
Error never seen before - HT-CT790

### ISSUE THREAD

**Issue by Jer-emy** [kovalev-sergey/homebridge-sony-audio#5]
Hello,

First, thank you for your plug-in.
Since today, I have an issue with it while it worked fine before.
I'm using this plug-in for a Sound Bar Sony HT-CT790 which is not present in your supported device list but it works as a HT-CT800 I think.

Below, the log when I restart homebridge on my Pi4:

> [12/04/2021, 23:59:52] [Sony Audio Platform] Adding new accessory: ��������������������������������
> [12/04/2021, 23:59:52] [Sony Audio Platform] Compatible device found, added: ��������������������������������
> (node:21601) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Accessory displayName cannot be longer than 63 bytes!
>     at Accessory.validateAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:948:13)
>     at Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1180:10)
>     at BridgeService.handlePublishExternalAccessories (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:442:20)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:21601) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)
> (node:21601) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> [12/04/2021, 23:59:53] [Sony Audio Platform] Incompatible device found, skipped: TV Salon

Do you have an idea to solve this issue?
Thank you in advance.

**Comment by kovalev-sergey** [comment]
hi @Jer-emy 
tell me what was the problem?

**Comment by Jer-emy** [comment]
Hi,

This issue has appeared when I've updated an other plug-in (Ewelink) and this morning, a new update was available for this other plug-in due to a bug inside. After updating, your plugin works fine.

So, it's not an issue in your plug-in :)
