### ISSUE TITLE
HT-ST5000 issues

### ISSUE THREAD

**Issue by Kroellie** [kovalev-sergey/homebridge-sony-audio#7]
Hi, first: absolutely great that you are working on this plugin, as a HT-ST5000 owner there is nothing else that remotely comes close to your plugin! Great job!

I've been experiencing some problems though, you might be able to help me with this:

First of all, in my network I have a lot of homebridge connected devices, but also a Philips Hue bridge. It seems that your plugin discovery notices the philips bridge as a device your plugin wants to connect with, see this error which is filling up my homebridge logs:

[7/27/2021, 10:45:13 AM] [Sony] Can't retrieve the device description at http://192.168.1.52/description.xml: TypeError: Cannot read property 'service' of undefined.
It looks like you have a problem in your network environment. All the same errors will be omitted.

Every second around 4 errors are being reported similar to this. So, the error will NOT be omitted in the case it should be ignored, but more importantly, why is it reporting?

Then, every now and then, when I restart homebridge, the icon in homekit of the HT-ST5000 will show as a power button, and 13 'off' accessories (the channels), however, when opening this button by long-press, no tiles are showing underneath. When I separate the tiles to individual tiles, all 13 of them show up with a home icon, but they don't 'do' anything, as if it was nothing. No switch, no button, nothing. When I restart homebridge, sometimes it gets fixed. Until it's not again. Let me know if you need a screenshot of this.

Would it be possible to 'fix' the connectivity to a single IP address, or MAC address instead of using discovery?
Would it be possible to eliminate some of the accessories by ignoring them, for example bluetooth, cast audio, dlna, etc...?

Thanks!

**Comment by Kroellie** [comment]
Note: I removed and reinstalled the plugin, and now after restarting a different error appears:

[7/27/2021, 10:58:05 AM] [Sony Audio Platform] Compatible device found, added: Sony
(node:18481) UnhandledPromiseRejectionWarning: Error: Accessory Sony experienced an address collision.
    at BridgeService.handlePublishExternalAccessories (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:417:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:18481) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by kovalev-sergey** [comment]
Hi @Kroellie 
Thanks for the kind words

> Can't retrieve the device description ...

I think I found the bug you are talking about. And fix it.

> UnhandledPromiseRejectionWarning: Error: Accessory Sony experienced an address collision. ...

The same

> Then, every now and then, when I restart homebridge, the icon in homekit of the HT-ST5000 will show as a power button, and 13 'off' accessories (the channels) ...

Do you mean this? [Can't see any inputs or inputs are shown as separat tiles with "home" icon](https://github.com/SeydX/homebridge-bravia-tvos/issues/108). The second title

> Would it be possible to 'fix' the connectivity to a single IP address, or MAC address instead of using discovery?

Simple answer - No, I can't do it. Plugin serves several different devices and I should get some internal information from device to control it. And  different devices have different settings that I get through discovery.

> Would it be possible to eliminate some of the accessories by ignoring them, for example bluetooth, cast audio, dlna, etc...?

it takes a long time (to do it well)
This feature is in the backlog ))
